repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: pretty-format-json
      - id: trailing-whitespace
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
  - repo: https://github.com/mpalmer/action-validator
    rev: v0.6.0
    hooks:
      - id: action-validator
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.88.16
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --results=verified,unknown --fail'
        language: system
        stages: [ "pre-commit", "pre-push" ]
  - repo: local
    hooks:
      - id: autopep8
        name: autopep8
        entry: uv
        language: system
        types: [ python ]
        require_serial: true
        args:
          [
            "run","python","-m","autopep8","--exclude",".venv","-ri","."
          ]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: uv
        language: system
        types: [ python ]
        require_serial: true
        args:
          [
            "run","python","-m","black","--fast","--color","-l","120","."
          ]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv
        language: system
        types: [ python ]
        require_serial: true
        args:
          [
            "run","python","-m","mypy","--exclude",".venv","--follow-untyped-imports","--explicit-package-bases","."
          ]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: uv
        language: system
        types: [ python ]
        require_serial: true
        args:
          [
            "run","python","-m","flake8","--exclude",".venv","--max-line-length","150","."
          ]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: uv
        language: system
        types: [ python ]
        require_serial: true
        args:
          [
            "run","python","-m","pylint","--ignore",".venv","--output-format=colorized",
            "--max-line-length","150","--fail-under","5","--fail-on","E","."
          ]
