repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: pretty-format-json
      - id: trailing-whitespace
  - repo: https://github.com/rhysd/actionlint
    hooks:
      - id: actionlint
  - repo: https://github.com/mpalmer/action-validator
    hooks:
      - id: action-validator
  - repo: https://github.com/trufflesecurity/trufflehog
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --results=verified,unknown --fail'
        language: system
        stages: [ "commit", "push" ]
  - repo: local
    hooks:
      - id: autopep8
        name: autopep8
        entry: uv
        language: system
        types: [ python ]
        require_serial: true
        args:
          [
            "run","python","-m","autopep8","--exclude",".venv","-ri","."
          ]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv
        language: system
        types: [ python ]
        require_serial: true
        args:
          [
            "run","python","-m","mypy","--exclude",".venv","--follow-untyped-imports","."
          ]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: uv
        language: system
        types: [ python ]
        require_serial: true
        args:
          [
            "run","python","-m","pylint","--ignore",".venv","--output-format=colorized","."
          ]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: uv
        language: system
        types: [ python ]
        require_serial: true
        args:
          [
            "run","python","-m","flake8","--exclude",".venv","--max-line-length","120","."
          ]
