# model-adjustments.yaml
adjustments:
  "Deepseek R1":
    priority: 95
    regex:
      - ".*deepseek[-_ ]{0,1}r1.*"
  "Search":
    priority: -100
    regex:
      - ".*search.*"
  "Distill":
    priority: -100
    regex:
      - ".*distill.*"
  "zero":
    priority: -100
    regex:
      - ".*zero.*"
  "mini":
    priority: -100
    regex:
      - ".*mini.*"
#  "No zero":
#    priority: 10
#    regex:
#      - "^(?!.*zero).*"
  "Embedding":
    priority: -10000
    regex:
      - ".*embed.*"
  "Image":
    priority: -10000
    regex:
      - ".*image.*"
  "TTS":
    priority: -10000
    regex:
      - ".*tts.*"
  "GPT-4o":
    priority: 91
    regex:
      - ".*gpt[-_ ]{0,1}4o.*"
  "GPT-4":
    priority: 90
    regex:
      - ".*gpt[-_ ]{0,1}4.*"
  "Claude 3.5 Sonnet":
    priority: 92
    regex:
      - ".*claude[-_ ]{0,1}3\\.5[-_ ]{0,1}sonnet.*"
  "Claude 3.5 Haiku":
    priority: 88
    regex:
      - ".*claude[-_ ]{0,1}3\\.5[-_ ]{0,1}haiku.*"
  "Claude 3 Opus":
    priority: 89
    regex:
      - ".*claude[-_ ]{0,1}3[-_ ]{0,1}opus.*"
  "Claude 3 Sonnet":
    priority: 87
    regex:
      - ".*claude[-_ ]{0,1}3[-_ ]{0,1}sonnet.*"
  "Claude 3 Haiku":
    priority: 85
    regex:
      - ".*claude[-_ ]{0,1}3[-_ ]{0,1}haiku.*"
  "Mixtral 8x22B":
    priority: 88
    regex:
      - ".*mixtral[-_ ]{0,1}8x22b.*"
  "Mixtral 8x7B":
    priority: 82
    regex:
      - ".*mixtral[-_ ]{0,1}8x7b.*"
  "Codestral":
    priority: 89
    regex:
      - ".*codestral.*"
  "Gemini Pro 1.5":
    priority: 87
    regex:
      - ".*gemini[-_ ]{0,1}pro[-_ ]{0,1}1\\.5.*"
  "Gemini Flash 1.5":
    priority: 85
    regex:
      - ".*gemini[-_ ]{0,1}flash[-_ ]{0,1}1\\.5.*"
  "Command R+":
    priority: 86
    regex:
      - ".*command[-_ ]{0,1}r\\+.*"
  "Command R":
    priority: 84
    regex:
      - ".*command[-_ ]{0,1}r.*"
  "Llama 3.3 70B":
    priority: 85
    regex:
      - ".*llama[-_ ]{0,1}3\\.3[-_ ]{0,1}70b.*"
  "Llama 3.1 70B":
    priority: 83
    regex:
      - ".*llama[-_ ]{0,1}3\\.1[-_ ]{0,1}70b.*"
  "Llama 3 70B":
    priority: 82
    regex:
      - ".*llama[-_ ]{0,1}3[-_ ]{0,1}70b.*"
  "Qwen 2.5 72B":
    priority: 83
    regex:
      - ".*qwen[-_ ]{0,1}2\\.5[-_ ]{0,1}72b.*"
  "Phi-3":
    priority: 84
    regex:
      - ".*phi[-_ ]{0,1}3.*"
  "Llama 2 70B":
    priority: 78
    regex:
      - ".*llama[-_ ]{0,1}2[-_ ]{0,1}70b.*"
  "Claude 2":
    priority: 78
    regex:
      - ".*claude[-_ ]{0,1}2.*"
  "GPT-3.5":
    priority: 75
    regex:
      - ".*gpt[-_ ]{0,1}3\\.5.*"
