name: Lint / Test / Check for Secrets
on: [pull_request, push]
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  lint-and-test:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/requirements*.txt
            **/uv.lock
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: autopep8
        if: always()
        run: uv run python -m autopep8 --exclude .venv -ri .
      - name: black
        if: always()
        run: uv run python -m black --fast --color -l 120 .
      - name: mypy
        if: always()
        run: uv run python -m mypy --exclude .venv --follow-untyped-imports --explicit-package-bases .
      - name: flake8
        if: always()
        run: uv run python -m flake8 --exclude .venv --max-line-length 120 .
      - name: pylint
        if: always()
        run: |
          uv run python -m pylint --ignore .venv --output-format=colorized \
          --max-line-length 120 --fail-under 5 --fail-on E .
      - name: Run tests
        if: always()
        run: uv run python -m pytest --color yes --verbosity=3
  truffle-hog:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "depth=$(($(jq length <<< '${{ toJson(github.event.commits) }}') + 2))" >> $GITHUB_ENV
            echo "branch=${{ github.ref_name }}" >> $GITHUB_ENV
          fi
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "depth=$((${{ github.event.pull_request.commits }}+2))" >> $GITHUB_ENV
            echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v4
        with:
          ref: ${{env.branch}}
          fetch-depth: ${{env.depth}}
      - uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown
